---
title: "Research"
---

I am mainly interested in the intersection of psychology of language, emotions and intergroup relations

## Papers

-   Wypych, M., & Bilewicz, M. (2022). Psychological toll of hate speech: The role of acculturation stress in the effects of exposure to ethnic slurs on mental health among Ukrainian immigrants in Poland. *Cultural Diversity and Ethnic Minority Psychology.* Advance online publication. [https://doi.org/10.1037/cdp0000522](https://psycnet.apa.org/doi/10.1037/cdp0000522)

-   Babińska, M., Bilewicz, M., Górska, P., Toruńczyk-Ruiz, S., & Wypych, M. (2022). Poles toward Ukrainians: The results of survey studies. *NAUKA*, (4). <http://www.nauka-pan.pl/index.php/nauka/article/view/982>

-   Wypych, M., Zochniak, K., & Bilewicz, M. (2020). Mowa nienawiści jako stygmatyzacja. Doświadczenie kontaktu z mową nienawiści wśród imigrantów w Polsce oraz studentów z zagranicy. *Kultura i Społeczeństwo*, *64*(3), 199-219. <https://www.ceeol.com/search/article-detail?id=986670>

-   Hansen, K., Wypych, M., Bańko, M., & Bilewicz, M. (2018). Psychological Determinants of Linguistic Purism: National Identification, Conservatism, and Attitudes to Loanwords. *Journal of Language and Social Psychology*, *37*(3), 365--375. <https://doi.org/10.1177/0261927X17737810>
